#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var}", "${var:-default}", "${var+SET}",
#           "${var#pattern}", "${var%pattern}", and "$( cmd )";
#         * compound commands having a testable exit status, especially "case";
#         * various built-in commands including "command", "set", and "shift";
#
#   (2) The binaries in GRADLE_APP_HOME/bin and GRADLE_HOME/bin must be on
#       your PATH as that is how the start up script finds Gradle.
#
#   Gradle will try to determine GRADLE_HOME automatically by reversing the
#   steps above in gradlew.
#
##############################################################################

# Express whether a file matches an extended regular expression.
if expr "$(basename "$0")" : '[A-Za-z0-9_]*$' >/dev/null ; then
    # This file is properly named and should be sourced by '. colon_script' or '. ./colon_script'.
    . "$(cd "$(dirname "$0")" && pwd)/gradle/wrapper/gradle-wrapper.sh"
else
    # Probably invoked with 'sh gradlew' and the path does not contain the script file exactly.
    echo "Error: path to gradlew does not match" >&2
    exit 1
fi
